language: node_js

node_js:
- "8"
- "10"
- "lts"

before_script: "node -v | grep -v v6 && npm run lint || :"
script: "npm run test:coverage"
after_success: "node -v | grep v12 && npm run coveralls"

jobs:
  include:
    - language: node_js
      node_js: 6
      script:
      - npm run test
