language: node_js

node_js:
- "8"
- "10"
- "node"

before_script: "npm run lint"
script: "npm run test:coverage"
after_success: "node -v | grep -v node && npm run coveralls"

jobs:
  include:
    - language: node_js
      node_js: 6
      script:
      - npm run test
